name: Python Tests with Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main # Run tests on pull requests targeting the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: comtacts
          auto-update-conda: true
          python-version: "3.10"

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate comtacts
          pip install -e ".[dev]"

      - name: Run tests
        run: |
          eval "$(conda shell.bash hook)"
          conda activate comtacts
          pytest --cov-report "xml:coverage.xml" --cov=src tests/
        shell: bash

      - name: Pytest Coverage Comment
        uses: MishaKav/pytest-coverage-comment@v1.1.48
        with:
          pytest-xml-coverage-path: ./coverage.xml
